name : github workflow dispatcher

on:
  workflow_dispatch:
    push:
        branches:
        - main
        - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to production server"